#define MPI_COMM_WORLD 0
#define MPI_COMM_SELF 1
#define MPI_GROUP_EMPTY 1
#define MPI_ERRORS_ARE_FATAL 1
#define MPI_ERRORS_RETURN 2
#define MPI_ERRORS_ABORT 3
#define MPI_MAX  1
#define MPI_MIN  2
#define MPI_SUM  3
#define MPI_PROD  4
#define MPI_LAND  5
#define MPI_BAND  6
#define MPI_LOR  7
#define MPI_BOR  8
#define MPI_LXOR  9
#define MPI_BXOR 10
#define MPI_MAXLOC 11
#define MPI_MINLOC 12
#define MPI_REPLACE 13
#define MPI_NO_OP 14
#define MPI_COMM_NULL 2
#define MPI_DATATYPE_NULL 0
#define MPI_ERRHANDLER_NULL 0
#define MPI_GROUP_NULL 0
#define MPI_INFO_NULL 0
#define MPI_MESSAGE_NULL 0
#define MPI_OP_NULL 0
#define MPI_REQUEST_NULL 0
#define MPI_WIN_NULL 0
#define MPI_MESSAGE_NULL 0
#define MPI_BYTE  1
#define MPI_PACKED  2
#define MPI_UB  3
#define MPI_LB  4
#define MPI_CHARACTER  5
#define MPI_LOGICAL  6
#define MPI_INTEGER  7
#define MPI_INTEGER1  8
#define MPI_INTEGER2  9
#define MPI_INTEGER4 10
#define MPI_INTEGER8 11
#define MPI_INTEGER16 12
#define MPI_REAL 13
#define MPI_REAL4 14
#define MPI_REAL8 15
#define MPI_REAL16 16
#define MPI_DOUBLE_PRECISION 17
#define MPI_COMPLEX 18
#define MPI_COMPLEX8 19
#define MPI_COMPLEX16 20
#define MPI_COMPLEX32 21
#define MPI_DOUBLE_COMPLEX 22
#define MPI_2REAL 23
#define MPI_2DOUBLE_PRECISION 24
#define MPI_2INTEGER 25
#define MPI_2COMPLEX 26
#define MPI_2DOUBLE_COMPLEX 27
#define MPI_REAL2 28
#define MPI_LOGICAL1 29
#define MPI_LOGICAL2 30
#define MPI_LOGICAL4 31
#define MPI_LOGICAL8 32
#define MPI_WCHAR 33
#define MPI_CHAR 34
#define MPI_UNSIGNED_CHAR 35
#define MPI_SIGNED_CHAR 36
#define MPI_SHORT 37
#define MPI_UNSIGNED_SHORT 38
#define MPI_INT 39
#define MPI_UNSIGNED 40
#define MPI_LONG 41
#define MPI_UNSIGNED_LONG 42
#define MPI_LONG_LONG_INT 43
#define MPI_LONG_LONG 43
#define MPI_UNSIGNED_LONG_LONG 44
#define MPI_FLOAT 45
#define MPI_DOUBLE 46
#define MPI_LONG_DOUBLE 47
#define MPI_FLOAT_INT 48
#define MPI_DOUBLE_INT 49
#define MPI_LONG_DOUBLE_INT 50
#define MPI_LONG_INT 51
#define MPI_2INT 52
#define MPI_SHORT_INT 53
#define MPI_CXX_BOOL 54
#define MPI_CXX_FLOAT_COMPLEX 55
#define MPI_CXX_COMPLEX 55
#define MPI_CXX_DOUBLE_COMPLEX 56
#define MPI_CXX_LONG_DOUBLE_COMPLEX 57
#define MPI_INT8_T 58
#define MPI_UINT8_T 59
#define MPI_INT16_T 60
#define MPI_UINT16_T 61
#define MPI_INT32_T 62
#define MPI_UINT32_T 63
#define MPI_INT64_T 64
#define MPI_UINT64_T 65
#define MPI_AINT 66
#define MPI_OFFSET 67
#define MPI_C_BOOL 68
#define MPI_C_COMPLEX 69
#define MPI_C_FLOAT_COMPLEX 69
#define MPI_C_DOUBLE_COMPLEX 70
#define MPI_C_LONG_DOUBLE_COMPLEX 71
#define MPI_COUNT 72
#define MPI_COMPLEX4 73
#define MPI_MESSAGE_NO_PROC 1
#define MPI_INFO_ENV 1
